import { env } from "cloudflare:workers";
import {
  neon,
  type NeonQueryFunction,
  type NeonQueryPromise,
  type FullQueryResults,
} from "@neondatabase/serverless";

type QueryResult = FullQueryResults<false>;
type BoundValue = string | number | boolean | null | undefined;

function connectionString() {
  const value = (env as unknown as { DATABASE_URL?: string }).DATABASE_URL;
  if (!value) {
    throw new Error(
      "DATABASE_URL is not configured. Use a Neon PostgreSQL connection string for this environment.",
    );
  }
  return value;
}

function toPostgresSql(source: string) {
  if (/^\s*PRAGMA\s+/i.test(source)) return null;

  let parameter = 0;
  let statement = source
    .replace(/INTEGER PRIMARY KEY AUTOINCREMENT/gi, "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY")
    .replace(/DEFAULT CURRENT_TIMESTAMP/gi, "DEFAULT (CURRENT_TIMESTAMP::text)")
    .replace(/= CURRENT_TIMESTAMP/gi, "= CURRENT_TIMESTAMP::text")
    .replace(/\bAS\s+([a-z][A-Za-z0-9]*[A-Z][A-Za-z0-9]*)\b/g, 'AS "$1"')
    .replace(/\?/g, () => `$${++parameter}`);

  const ignoreConflict = /^\s*INSERT\s+OR\s+IGNORE\s+INTO\s+/i.test(statement);
  statement = statement.replace(/^\s*INSERT\s+OR\s+IGNORE\s+INTO\s+/i, "INSERT INTO ");
  if (ignoreConflict) statement = `${statement.replace(/;\s*$/, "")} ON CONFLICT DO NOTHING`;
  return statement;
}

function normalizeRow<T>(row: Record<string, unknown> | undefined): T | null {
  if (!row) return null;
  if (typeof row.count === "string" && /^\d+$/.test(row.count)) row.count = Number(row.count);
  return row as T;
}

export class PostgresPreparedStatement {
  private values: BoundValue[] = [];

  constructor(
    private readonly sql: NeonQueryFunction<false, true>,
    private readonly source: string,
  ) {}

  bind(...values: BoundValue[]) {
    this.values = values;
    return this;
  }

  asQuery(): NeonQueryPromise<false, true, QueryResult> | null {
    const statement = toPostgresSql(this.source);
    if (!statement) return null;
    return this.sql.query(statement, this.values);
  }

  async all<T = Record<string, unknown>>() {
    const query = this.asQuery();
    if (!query) return { results: [] as T[] };
    const result = await query;
    return { results: result.rows as T[] };
  }

  async first<T = Record<string, unknown>>() {
    const query = this.asQuery();
    if (!query) return null;
    const result = await query;
    return normalizeRow<T>(result.rows[0] as Record<string, unknown> | undefined);
  }

  async run() {
    const query = this.asQuery();
    if (!query) return { success: true, meta: { changes: 0 } };
    const result = await query;
    return { success: true, meta: { changes: result.rowCount } };
  }
}

export class PostgresDatabase {
  private readonly sql = neon(connectionString(), { fullResults: true });

  prepare(statement: string) {
    return new PostgresPreparedStatement(this.sql, statement);
  }

  async batch(statements: PostgresPreparedStatement[]) {
    const queries = statements
      .map((statement) => statement.asQuery())
      .filter((query): query is NeonQueryPromise<false, true, QueryResult> => query !== null);
    if (queries.length === 0) return [];
    return this.sql.transaction(queries);
  }
}

let database: PostgresDatabase | undefined;

export function getPostgres() {
  database ??= new PostgresDatabase();
  return database;
}
